# coding: utf-8

"""
    HiddenLayer ModelScan V2

    HiddenLayer ModelScan API for scanning of models

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from hiddenlayer.sdk.rest.models.gguf_file_attributes import GGUFFileAttributes
from hiddenlayer.sdk.rest.models.keras_file_attributes import KerasFileAttributes
from hiddenlayer.sdk.rest.models.numpy_file_attributes import NumpyFileAttributes
from hiddenlayer.sdk.rest.models.rds_file_attributes import RDSFileAttributes
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

FILETYPEDETAILS_ONE_OF_SCHEMAS = ["GGUFFileAttributes", "KerasFileAttributes", "NumpyFileAttributes", "RDSFileAttributes"]

class FileTypeDetails(BaseModel):
    """
    FileTypeDetails
    """
    # data type: GGUFFileAttributes
    oneof_schema_1_validator: Optional[GGUFFileAttributes] = None
    # data type: KerasFileAttributes
    oneof_schema_2_validator: Optional[KerasFileAttributes] = None
    # data type: NumpyFileAttributes
    oneof_schema_3_validator: Optional[NumpyFileAttributes] = None
    # data type: RDSFileAttributes
    oneof_schema_4_validator: Optional[RDSFileAttributes] = None
    actual_instance: Optional[Union[GGUFFileAttributes, KerasFileAttributes, NumpyFileAttributes, RDSFileAttributes]] = None
    one_of_schemas: Set[str] = { "GGUFFileAttributes", "KerasFileAttributes", "NumpyFileAttributes", "RDSFileAttributes" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = FileTypeDetails.model_construct()
        error_messages = []
        match = 0
        # validate data type: GGUFFileAttributes
        if not isinstance(v, GGUFFileAttributes):
            error_messages.append(f"Error! Input type `{type(v)}` is not `GGUFFileAttributes`")
        else:
            match += 1
        # validate data type: KerasFileAttributes
        if not isinstance(v, KerasFileAttributes):
            error_messages.append(f"Error! Input type `{type(v)}` is not `KerasFileAttributes`")
        else:
            match += 1
        # validate data type: NumpyFileAttributes
        if not isinstance(v, NumpyFileAttributes):
            error_messages.append(f"Error! Input type `{type(v)}` is not `NumpyFileAttributes`")
        else:
            match += 1
        # validate data type: RDSFileAttributes
        if not isinstance(v, RDSFileAttributes):
            error_messages.append(f"Error! Input type `{type(v)}` is not `RDSFileAttributes`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in FileTypeDetails with oneOf schemas: GGUFFileAttributes, KerasFileAttributes, NumpyFileAttributes, RDSFileAttributes. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in FileTypeDetails with oneOf schemas: GGUFFileAttributes, KerasFileAttributes, NumpyFileAttributes, RDSFileAttributes. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into GGUFFileAttributes
        try:
            instance.actual_instance = GGUFFileAttributes.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into KerasFileAttributes
        try:
            instance.actual_instance = KerasFileAttributes.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into NumpyFileAttributes
        try:
            instance.actual_instance = NumpyFileAttributes.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into RDSFileAttributes
        try:
            instance.actual_instance = RDSFileAttributes.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into FileTypeDetails with oneOf schemas: GGUFFileAttributes, KerasFileAttributes, NumpyFileAttributes, RDSFileAttributes. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into FileTypeDetails with oneOf schemas: GGUFFileAttributes, KerasFileAttributes, NumpyFileAttributes, RDSFileAttributes. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], GGUFFileAttributes, KerasFileAttributes, NumpyFileAttributes, RDSFileAttributes]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


