# coding: utf-8

"""
    HiddenLayer ModelScan V2

    HiddenLayer ModelScan API for scanning of models

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class KerasFileAttributes(BaseModel):
    """
    KerasFileAttributes
    """ # noqa: E501
    subtype: List[StrictStr]
    keras_version: Optional[StrictStr] = Field(default=None, description="version of the Keras file")
    pickle_modules: List[StrictStr]
    keras_class_name: Optional[StrictStr] = None
    keras_date_saved_at: Optional[StrictStr] = None
    keras_module: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["subtype", "keras_version", "pickle_modules", "keras_class_name", "keras_date_saved_at", "keras_module"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of KerasFileAttributes from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of KerasFileAttributes from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "subtype": obj.get("subtype"),
            "keras_version": obj.get("keras_version"),
            "pickle_modules": obj.get("pickle_modules"),
            "keras_class_name": obj.get("keras_class_name"),
            "keras_date_saved_at": obj.get("keras_date_saved_at"),
            "keras_module": obj.get("keras_module")
        })
        return _obj


