"""Auto-generated registry of beta endpoints.

DO NOT EDIT -- regenerated by scripts/utils/generate-beta-endpoints.cjs

Maps URL paths to qualified method names for runtime warnings.
"""
from __future__ import annotations

BETA_ENDPOINTS: dict[str, str] = {
    "/detection/v2/request-evaluations": "DetectionResource.request_evaluation",
    "/detection/v2/response-evaluations": "DetectionResource.response_evaluation",
}
