"""Auto-generated registry of beta endpoints.

DO NOT EDIT -- regenerated by scripts/utils/generate-beta-endpoints.cjs

Each entry is a (path pattern, qualified method name) pair. A path pattern is a
tuple of segments where a string is a literal match and None is a wildcard that
matches any single path-parameter segment. Used for runtime beta warnings.
"""

from __future__ import annotations

BETA_ENDPOINTS: list[tuple[tuple[str | None, ...], str]] = [
    (("detection", "v2", "interaction-evaluations"), "RuntimeResource.evaluate_interaction"),
    (("detection", "v2", "request-evaluations"), "RuntimeResource.evaluate_request"),
    (("detection", "v2", "response-evaluations"), "RuntimeResource.evaluate_response"),
    (("evaluations", "v1", "jobs", None, "termination"), "RedTeamResource.terminate"),
    (("evaluations", "v1", "red-team"), "RedTeamResource.create"),
    (("evaluations", "v1", "red-team", None), "RedTeamResource.retrieve_evaluation_results"),
    (("evaluations", "v1", "red-team", None, "next-action"), "RedTeamResource.retrieve_next_action"),
    (("evaluations", "v1", "red-team", None, "status"), "RedTeamResource.retrieve_status"),
    (("evaluations", "v1", "red-team", None, "target-response"), "RedTeamResource.submit_target_response"),
]
