configured_endpoints: 18
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/hiddenlayer%2Fhiddenlayer-sdk-5c2d5bbe92f77bccf956f4b64e0167ddbebd91369ada3148d91daa299e1a4c6a.yml
openapi_spec_hash: bf5bff20e4e89ae3b986e89361acb65c
config_hash: 058872b126c8fa1b4e349b2bee0eacb3
