configured_endpoints: 18
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/hiddenlayer%2Fhiddenlayer-sdk-796c4c8465ffbae6d7735894cae3149d6baba98b360efe0b328a5ca25bafa21d.yml
openapi_spec_hash: 18fac6e4eede9093b3e55d49f387db3f
config_hash: 058872b126c8fa1b4e349b2bee0eacb3
