configured_endpoints: 16
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/hiddenlayer%2Fhiddenlayer-sdk-52efbd2144feba1b8b8c5ab4bbed4eeea79bb493b36a4966f8aeef8f4d6525ba.yml
openapi_spec_hash: 48d969134fd5e154c79dffcd4de0ba85
config_hash: b2731ad6d674191b5d68fb6e05f8959c
