configured_endpoints: 18
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/hiddenlayer%2Fhiddenlayer-sdk-9e6dea2f7af2ca7eea1a207fc530d5adbc1b535afa78a853a6575e4ffa952581.yml
openapi_spec_hash: c8dd7caced3edde880b3dfeb3576b07c
config_hash: e809c91ce00acee9930f6cca1cd7774a
