configured_endpoints: 18
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/hiddenlayer%2Fhiddenlayer-sdk-e36dc7c0bcbbcad9dfad092dff251cef955789aadeea424998674a4366086c91.yml
openapi_spec_hash: 388fb3227dc09a36462df9d0f1b9d0de
config_hash: e809c91ce00acee9930f6cca1cd7774a
