# coding: utf-8

"""
    HiddenLayer ModelScan

    HiddenLayer ModelScan API for scanning of models

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hiddenlayer.sdk.rest.models.get_multipart_upload_response import GetMultipartUploadResponse

class TestGetMultipartUploadResponse(unittest.TestCase):
    """GetMultipartUploadResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetMultipartUploadResponse:
        """Test GetMultipartUploadResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetMultipartUploadResponse`
        """
        model = GetMultipartUploadResponse()
        if include_optional:
            return GetMultipartUploadResponse(
                upload_id = '',
                parts = [
                    hiddenlayer.sdk.rest.models.multipart_upload_part.Multipart Upload Part(
                        part_number = 1.337, 
                        start_offset = 1.337, 
                        end_offset = 1.337, )
                    ]
            )
        else:
            return GetMultipartUploadResponse(
                upload_id = '',
                parts = [
                    hiddenlayer.sdk.rest.models.multipart_upload_part.Multipart Upload Part(
                        part_number = 1.337, 
                        start_offset = 1.337, 
                        end_offset = 1.337, )
                    ],
        )
        """

    def testGetMultipartUploadResponse(self):
        """Test GetMultipartUploadResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
