# coding: utf-8

"""
    HiddenLayer ModelScan

    HiddenLayer ModelScan API for scanning of models

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hiddenlayer.rest.api.mldr_api import MldrApi


class TestMldrApi(unittest.TestCase):
    """MldrApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MldrApi()

    def tearDown(self) -> None:
        pass

    def test_submit_vectors(self) -> None:
        """Test case for submit_vectors

        Submit vectors
        """
        pass


if __name__ == '__main__':
    unittest.main()
