# coding: utf-8

"""
    HiddenLayer ModelScan V2

    HiddenLayer ModelScan API for scanning of models

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hiddenlayer.sdk.rest.models.numpy_file_attributes import NumpyFileAttributes

class TestNumpyFileAttributes(unittest.TestCase):
    """NumpyFileAttributes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NumpyFileAttributes:
        """Test NumpyFileAttributes
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NumpyFileAttributes`
        """
        model = NumpyFileAttributes()
        if include_optional:
            return NumpyFileAttributes(
                subtype = [
                    ''
                    ],
                numpy_arrays = '3',
                numpy_shape = ["[4, 4]","[1, 1]","[1, 100]"]
            )
        else:
            return NumpyFileAttributes(
                subtype = [
                    ''
                    ],
                numpy_arrays = '3',
                numpy_shape = ["[4, 4]","[1, 1]","[1, 100]"],
        )
        """

    def testNumpyFileAttributes(self):
        """Test NumpyFileAttributes"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
