# coding: utf-8

"""
    HiddenLayer-API

    HiddenLayer-API

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hiddenlayer.sdk.rest.models.mitre_atlas_inner import MITREAtlasInner

class TestMITREAtlasInner(unittest.TestCase):
    """MITREAtlasInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MITREAtlasInner:
        """Test MITREAtlasInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MITREAtlasInner`
        """
        model = MITREAtlasInner()
        if include_optional:
            return MITREAtlasInner(
                technique = 'AML.T0480Z#UM/?R,Fp^l6$ARjbhJk C>i H'qT\\{<?'es#)#iK.YM{Rag2/!KB!k@5oXh.:Ts\";mGL,i&z5[',
                tactic = 'AML.TA4807'
            )
        else:
            return MITREAtlasInner(
        )
        """

    def testMITREAtlasInner(self):
        """Test MITREAtlasInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
