# coding: utf-8

"""
    HiddenLayer Sensor SOR

    HiddenLayer Sensor SOR API for operations to sensor data storage

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hiddenlayer.sdk.rest.models.notify_model_scan_completed200_response import NotifyModelScanCompleted200Response

class TestNotifyModelScanCompleted200Response(unittest.TestCase):
    """NotifyModelScanCompleted200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NotifyModelScanCompleted200Response:
        """Test NotifyModelScanCompleted200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NotifyModelScanCompleted200Response`
        """
        model = NotifyModelScanCompleted200Response()
        if include_optional:
            return NotifyModelScanCompleted200Response(
                message = ''
            )
        else:
            return NotifyModelScanCompleted200Response(
                message = '',
        )
        """

    def testNotifyModelScanCompleted200Response(self):
        """Test NotifyModelScanCompleted200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
