# coding: utf-8

"""
    HiddenLayer-API

    HiddenLayer-API

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hiddenlayer.sdk.rest.models.model_version import ModelVersion

class TestModelVersion(unittest.TestCase):
    """ModelVersion unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModelVersion:
        """Test ModelVersion
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModelVersion`
        """
        model = ModelVersion()
        if include_optional:
            return ModelVersion(
                model_version_id = '',
                version = '1',
                tags = {"env":"staging","owner":"research"},
                locations = {"hl_s3":"https://hl-tenant-models.s3.amazonaws.com/03289d66-71ab-11ee-b530-7ecb4245a394/12345678-1234-1234-1234-123456789012/87654321-4321-4321-4321-210987654321/model","azure":"https://myaccount.blob.core.windows.net/mycontainer/myvirtualdirectory/model"},
                multi_file = True,
                retrievable = True
            )
        else:
            return ModelVersion(
                version = '1',
        )
        """

    def testModelVersion(self):
        """Test ModelVersion"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
