# coding: utf-8

"""
    HiddenLayer Sensor SOR

    HiddenLayer Sensor SOR API for operations to sensor data storage

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hiddenlayer.sdk.rest.models.reporting_descriptor_relationship import ReportingDescriptorRelationship

class TestReportingDescriptorRelationship(unittest.TestCase):
    """ReportingDescriptorRelationship unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReportingDescriptorRelationship:
        """Test ReportingDescriptorRelationship
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReportingDescriptorRelationship`
        """
        model = ReportingDescriptorRelationship()
        if include_optional:
            return ReportingDescriptorRelationship(
                target = hiddenlayer.sdk.rest.models.reporting_descriptor_reference.reportingDescriptorReference(
                    id = '', 
                    index = -1, 
                    guid = '62ECB020-8429-10cc-81FF-CCfeEe150AC3', 
                    tool_component = hiddenlayer.sdk.rest.models.tool_component_reference.toolComponentReference(
                        name = '', 
                        index = -1, 
                        guid = '62ECB020-8429-10cc-81FF-CCfeEe150AC3', 
                        properties = { }, ), 
                    properties = { }, ),
                kinds = [
                    ''
                    ],
                description = hiddenlayer.sdk.rest.models.message.message(
                    text = '', 
                    markdown = '', 
                    id = '', 
                    arguments = [
                        ''
                        ], 
                    properties = { }, ),
                properties = { }
            )
        else:
            return ReportingDescriptorRelationship(
                target = hiddenlayer.sdk.rest.models.reporting_descriptor_reference.reportingDescriptorReference(
                    id = '', 
                    index = -1, 
                    guid = '62ECB020-8429-10cc-81FF-CCfeEe150AC3', 
                    tool_component = hiddenlayer.sdk.rest.models.tool_component_reference.toolComponentReference(
                        name = '', 
                        index = -1, 
                        guid = '62ECB020-8429-10cc-81FF-CCfeEe150AC3', 
                        properties = { }, ), 
                    properties = { }, ),
        )
        """

    def testReportingDescriptorRelationship(self):
        """Test ReportingDescriptorRelationship"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
