# coding: utf-8

"""
    HiddenLayer ModelScan V2

    HiddenLayer ModelScan API for scanning of models

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hiddenlayer.sdk.rest.models.tool_component_reference import ToolComponentReference

class TestToolComponentReference(unittest.TestCase):
    """ToolComponentReference unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ToolComponentReference:
        """Test ToolComponentReference
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ToolComponentReference`
        """
        model = ToolComponentReference()
        if include_optional:
            return ToolComponentReference(
                name = '',
                index = -1,
                guid = '62ECB020-8429-10cc-81FF-CCfeEe150AC3',
                properties = { }
            )
        else:
            return ToolComponentReference(
        )
        """

    def testToolComponentReference(self):
        """Test ToolComponentReference"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
