# coding: utf-8

"""
    HiddenLayer ModelScan V2

    HiddenLayer ModelScan API for scanning of models

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hiddenlayer.sdk.rest.models.keras_file_attributes import KerasFileAttributes

class TestKerasFileAttributes(unittest.TestCase):
    """KerasFileAttributes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> KerasFileAttributes:
        """Test KerasFileAttributes
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `KerasFileAttributes`
        """
        model = KerasFileAttributes()
        if include_optional:
            return KerasFileAttributes(
                subtype = [
                    ''
                    ],
                keras_version = '2.11.0,2.11.0',
                pickle_modules = [
                    ''
                    ],
                keras_class_name = '',
                keras_date_saved_at = '',
                keras_module = ''
            )
        else:
            return KerasFileAttributes(
                subtype = [
                    ''
                    ],
                pickle_modules = [
                    ''
                    ],
        )
        """

    def testKerasFileAttributes(self):
        """Test KerasFileAttributes"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
