# coding: utf-8

"""
    HiddenLayer ModelScan

    HiddenLayer ModelScan API for scanning of models

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hiddenlayer.rest.models.sensor_sor_query_response import SensorSORQueryResponse

class TestSensorSORQueryResponse(unittest.TestCase):
    """SensorSORQueryResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SensorSORQueryResponse:
        """Test SensorSORQueryResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SensorSORQueryResponse`
        """
        model = SensorSORQueryResponse()
        if include_optional:
            return SensorSORQueryResponse(
                total_count = 56,
                page_size = 56,
                page_number = 56,
                results = [
                    null
                    ]
            )
        else:
            return SensorSORQueryResponse(
                total_count = 56,
                page_size = 56,
                page_number = 56,
                results = [
                    null
                    ],
        )
        """

    def testSensorSORQueryResponse(self):
        """Test SensorSORQueryResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
