# coding: utf-8

"""
    HiddenLayer-API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hiddenlayer.sdk.rest.models.external_property_file_references import ExternalPropertyFileReferences

class TestExternalPropertyFileReferences(unittest.TestCase):
    """ExternalPropertyFileReferences unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExternalPropertyFileReferences:
        """Test ExternalPropertyFileReferences
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExternalPropertyFileReferences`
        """
        model = ExternalPropertyFileReferences()
        if include_optional:
            return ExternalPropertyFileReferences(
                conversion = hiddenlayer.sdk.rest.models.external_property_file_reference.externalPropertyFileReference(
                    location = hiddenlayer.sdk.rest.models.artifact_location.artifactLocation(
                        uri = '', 
                        uri_base_id = '', 
                        index = -1, 
                        description = hiddenlayer.sdk.rest.models.message.message(
                            text = '', 
                            markdown = '', 
                            id = '', 
                            arguments = [
                                ''
                                ], 
                            properties = { }, ), 
                        properties = { }, ), 
                    guid = '62ECB020-8429-10cc-81FF-CCfeEe150AC3', 
                    item_count = -1, 
                    properties = , ),
                graphs = [
                    hiddenlayer.sdk.rest.models.external_property_file_reference.externalPropertyFileReference(
                        location = hiddenlayer.sdk.rest.models.artifact_location.artifactLocation(
                            uri = '', 
                            uri_base_id = '', 
                            index = -1, 
                            description = hiddenlayer.sdk.rest.models.message.message(
                                text = '', 
                                markdown = '', 
                                id = '', 
                                arguments = [
                                    ''
                                    ], 
                                properties = { }, ), 
                            properties = { }, ), 
                        guid = '62ECB020-8429-10cc-81FF-CCfeEe150AC3', 
                        item_count = -1, 
                        properties = , )
                    ],
                externalized_properties = hiddenlayer.sdk.rest.models.external_property_file_reference.externalPropertyFileReference(
                    location = hiddenlayer.sdk.rest.models.artifact_location.artifactLocation(
                        uri = '', 
                        uri_base_id = '', 
                        index = -1, 
                        description = hiddenlayer.sdk.rest.models.message.message(
                            text = '', 
                            markdown = '', 
                            id = '', 
                            arguments = [
                                ''
                                ], 
                            properties = { }, ), 
                        properties = { }, ), 
                    guid = '62ECB020-8429-10cc-81FF-CCfeEe150AC3', 
                    item_count = -1, 
                    properties = , ),
                artifacts = [
                    hiddenlayer.sdk.rest.models.external_property_file_reference.externalPropertyFileReference(
                        location = hiddenlayer.sdk.rest.models.artifact_location.artifactLocation(
                            uri = '', 
                            uri_base_id = '', 
                            index = -1, 
                            description = hiddenlayer.sdk.rest.models.message.message(
                                text = '', 
                                markdown = '', 
                                id = '', 
                                arguments = [
                                    ''
                                    ], 
                                properties = { }, ), 
                            properties = { }, ), 
                        guid = '62ECB020-8429-10cc-81FF-CCfeEe150AC3', 
                        item_count = -1, 
                        properties = , )
                    ],
                invocations = [
                    hiddenlayer.sdk.rest.models.external_property_file_reference.externalPropertyFileReference(
                        location = hiddenlayer.sdk.rest.models.artifact_location.artifactLocation(
                            uri = '', 
                            uri_base_id = '', 
                            index = -1, 
                            description = hiddenlayer.sdk.rest.models.message.message(
                                text = '', 
                                markdown = '', 
                                id = '', 
                                arguments = [
                                    ''
                                    ], 
                                properties = { }, ), 
                            properties = { }, ), 
                        guid = '62ECB020-8429-10cc-81FF-CCfeEe150AC3', 
                        item_count = -1, 
                        properties = , )
                    ],
                logical_locations = [
                    hiddenlayer.sdk.rest.models.external_property_file_reference.externalPropertyFileReference(
                        location = hiddenlayer.sdk.rest.models.artifact_location.artifactLocation(
                            uri = '', 
                            uri_base_id = '', 
                            index = -1, 
                            description = hiddenlayer.sdk.rest.models.message.message(
                                text = '', 
                                markdown = '', 
                                id = '', 
                                arguments = [
                                    ''
                                    ], 
                                properties = { }, ), 
                            properties = { }, ), 
                        guid = '62ECB020-8429-10cc-81FF-CCfeEe150AC3', 
                        item_count = -1, 
                        properties = , )
                    ],
                thread_flow_locations = [
                    hiddenlayer.sdk.rest.models.external_property_file_reference.externalPropertyFileReference(
                        location = hiddenlayer.sdk.rest.models.artifact_location.artifactLocation(
                            uri = '', 
                            uri_base_id = '', 
                            index = -1, 
                            description = hiddenlayer.sdk.rest.models.message.message(
                                text = '', 
                                markdown = '', 
                                id = '', 
                                arguments = [
                                    ''
                                    ], 
                                properties = { }, ), 
                            properties = { }, ), 
                        guid = '62ECB020-8429-10cc-81FF-CCfeEe150AC3', 
                        item_count = -1, 
                        properties = , )
                    ],
                results = [
                    hiddenlayer.sdk.rest.models.external_property_file_reference.externalPropertyFileReference(
                        location = hiddenlayer.sdk.rest.models.artifact_location.artifactLocation(
                            uri = '', 
                            uri_base_id = '', 
                            index = -1, 
                            description = hiddenlayer.sdk.rest.models.message.message(
                                text = '', 
                                markdown = '', 
                                id = '', 
                                arguments = [
                                    ''
                                    ], 
                                properties = { }, ), 
                            properties = { }, ), 
                        guid = '62ECB020-8429-10cc-81FF-CCfeEe150AC3', 
                        item_count = -1, 
                        properties = , )
                    ],
                taxonomies = [
                    hiddenlayer.sdk.rest.models.external_property_file_reference.externalPropertyFileReference(
                        location = hiddenlayer.sdk.rest.models.artifact_location.artifactLocation(
                            uri = '', 
                            uri_base_id = '', 
                            index = -1, 
                            description = hiddenlayer.sdk.rest.models.message.message(
                                text = '', 
                                markdown = '', 
                                id = '', 
                                arguments = [
                                    ''
                                    ], 
                                properties = { }, ), 
                            properties = { }, ), 
                        guid = '62ECB020-8429-10cc-81FF-CCfeEe150AC3', 
                        item_count = -1, 
                        properties = , )
                    ],
                addresses = [
                    hiddenlayer.sdk.rest.models.external_property_file_reference.externalPropertyFileReference(
                        location = hiddenlayer.sdk.rest.models.artifact_location.artifactLocation(
                            uri = '', 
                            uri_base_id = '', 
                            index = -1, 
                            description = hiddenlayer.sdk.rest.models.message.message(
                                text = '', 
                                markdown = '', 
                                id = '', 
                                arguments = [
                                    ''
                                    ], 
                                properties = { }, ), 
                            properties = { }, ), 
                        guid = '62ECB020-8429-10cc-81FF-CCfeEe150AC3', 
                        item_count = -1, 
                        properties = , )
                    ],
                driver = hiddenlayer.sdk.rest.models.external_property_file_reference.externalPropertyFileReference(
                    location = hiddenlayer.sdk.rest.models.artifact_location.artifactLocation(
                        uri = '', 
                        uri_base_id = '', 
                        index = -1, 
                        description = hiddenlayer.sdk.rest.models.message.message(
                            text = '', 
                            markdown = '', 
                            id = '', 
                            arguments = [
                                ''
                                ], 
                            properties = { }, ), 
                        properties = { }, ), 
                    guid = '62ECB020-8429-10cc-81FF-CCfeEe150AC3', 
                    item_count = -1, 
                    properties = , ),
                extensions = [
                    hiddenlayer.sdk.rest.models.external_property_file_reference.externalPropertyFileReference(
                        location = hiddenlayer.sdk.rest.models.artifact_location.artifactLocation(
                            uri = '', 
                            uri_base_id = '', 
                            index = -1, 
                            description = hiddenlayer.sdk.rest.models.message.message(
                                text = '', 
                                markdown = '', 
                                id = '', 
                                arguments = [
                                    ''
                                    ], 
                                properties = { }, ), 
                            properties = { }, ), 
                        guid = '62ECB020-8429-10cc-81FF-CCfeEe150AC3', 
                        item_count = -1, 
                        properties = , )
                    ],
                policies = [
                    hiddenlayer.sdk.rest.models.external_property_file_reference.externalPropertyFileReference(
                        location = hiddenlayer.sdk.rest.models.artifact_location.artifactLocation(
                            uri = '', 
                            uri_base_id = '', 
                            index = -1, 
                            description = hiddenlayer.sdk.rest.models.message.message(
                                text = '', 
                                markdown = '', 
                                id = '', 
                                arguments = [
                                    ''
                                    ], 
                                properties = { }, ), 
                            properties = { }, ), 
                        guid = '62ECB020-8429-10cc-81FF-CCfeEe150AC3', 
                        item_count = -1, 
                        properties = , )
                    ],
                translations = [
                    hiddenlayer.sdk.rest.models.external_property_file_reference.externalPropertyFileReference(
                        location = hiddenlayer.sdk.rest.models.artifact_location.artifactLocation(
                            uri = '', 
                            uri_base_id = '', 
                            index = -1, 
                            description = hiddenlayer.sdk.rest.models.message.message(
                                text = '', 
                                markdown = '', 
                                id = '', 
                                arguments = [
                                    ''
                                    ], 
                                properties = { }, ), 
                            properties = { }, ), 
                        guid = '62ECB020-8429-10cc-81FF-CCfeEe150AC3', 
                        item_count = -1, 
                        properties = , )
                    ],
                web_requests = [
                    hiddenlayer.sdk.rest.models.external_property_file_reference.externalPropertyFileReference(
                        location = hiddenlayer.sdk.rest.models.artifact_location.artifactLocation(
                            uri = '', 
                            uri_base_id = '', 
                            index = -1, 
                            description = hiddenlayer.sdk.rest.models.message.message(
                                text = '', 
                                markdown = '', 
                                id = '', 
                                arguments = [
                                    ''
                                    ], 
                                properties = { }, ), 
                            properties = { }, ), 
                        guid = '62ECB020-8429-10cc-81FF-CCfeEe150AC3', 
                        item_count = -1, 
                        properties = , )
                    ],
                web_responses = [
                    hiddenlayer.sdk.rest.models.external_property_file_reference.externalPropertyFileReference(
                        location = hiddenlayer.sdk.rest.models.artifact_location.artifactLocation(
                            uri = '', 
                            uri_base_id = '', 
                            index = -1, 
                            description = hiddenlayer.sdk.rest.models.message.message(
                                text = '', 
                                markdown = '', 
                                id = '', 
                                arguments = [
                                    ''
                                    ], 
                                properties = { }, ), 
                            properties = { }, ), 
                        guid = '62ECB020-8429-10cc-81FF-CCfeEe150AC3', 
                        item_count = -1, 
                        properties = , )
                    ],
                properties = { }
            )
        else:
            return ExternalPropertyFileReferences(
        )
        """

    def testExternalPropertyFileReferences(self):
        """Test ExternalPropertyFileReferences"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
