# coding: utf-8

"""
    HiddenLayer-API

    HiddenLayer-API

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hiddenlayer.sdk.rest.models.multi_file_upload_request_v3 import MultiFileUploadRequestV3

class TestMultiFileUploadRequestV3(unittest.TestCase):
    """MultiFileUploadRequestV3 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MultiFileUploadRequestV3:
        """Test MultiFileUploadRequestV3
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MultiFileUploadRequestV3`
        """
        model = MultiFileUploadRequestV3()
        if include_optional:
            return MultiFileUploadRequestV3(
                model_version = '',
                model_name = '',
                requesting_entity = '',
                location_alias = ''
            )
        else:
            return MultiFileUploadRequestV3(
                model_version = '',
                model_name = '',
                requesting_entity = '',
        )
        """

    def testMultiFileUploadRequestV3(self):
        """Test MultiFileUploadRequestV3"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
