# coding: utf-8

"""
    HiddenLayer ModelScan

    HiddenLayer ModelScan API for scanning of models

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hiddenlayer.rest.models.scan_model_request import ScanModelRequest

class TestScanModelRequest(unittest.TestCase):
    """ScanModelRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ScanModelRequest:
        """Test ScanModelRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ScanModelRequest`
        """
        model = ScanModelRequest()
        if include_optional:
            return ScanModelRequest(
                location = ''
            )
        else:
            return ScanModelRequest(
                location = '',
        )
        """

    def testScanModelRequest(self):
        """Test ScanModelRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
