# coding: utf-8

"""
    HiddenLayer Sensor SOR

    HiddenLayer Sensor SOR API for operations to sensor data storage

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hiddenlayer.sdk.rest.models.sensor_sor_query_filter import SensorSORQueryFilter

class TestSensorSORQueryFilter(unittest.TestCase):
    """SensorSORQueryFilter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SensorSORQueryFilter:
        """Test SensorSORQueryFilter
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SensorSORQueryFilter`
        """
        model = SensorSORQueryFilter()
        if include_optional:
            return SensorSORQueryFilter(
                plaintext_name = '',
                active = True,
                version = 56,
                created_at_start = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                created_at_stop = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                source = 'adhoc'
            )
        else:
            return SensorSORQueryFilter(
        )
        """

    def testSensorSORQueryFilter(self):
        """Test SensorSORQueryFilter"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
