# coding: utf-8

"""
    HiddenLayer ModelScan V2

    HiddenLayer ModelScan API for scanning of models

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hiddenlayer.sdk.rest.api.model_supply_chain_api import ModelSupplyChainApi


class TestModelSupplyChainApi(unittest.TestCase):
    """ModelSupplyChainApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ModelSupplyChainApi()

    def tearDown(self) -> None:
        pass

    def test_begin_multi_file_upload(self) -> None:
        """Test case for begin_multi_file_upload

        Start V3 Upload
        """
        pass

    def test_begin_multipart_file_upload(self) -> None:
        """Test case for begin_multipart_file_upload

        Add file to V3 Upload
        """
        pass

    def test_complete_multi_file_upload(self) -> None:
        """Test case for complete_multi_file_upload

        Indicate All files are uploaded and start the scan
        """
        pass

    def test_complete_multipart_file_upload(self) -> None:
        """Test case for complete_multipart_file_upload

        Indicate that upload is completed for {file_id}
        """
        pass

    def test_create_scan_job(self) -> None:
        """Test case for create_scan_job

        Request a Model Scan Job
        """
        pass

    def test_get_condensed_model_scan_reports(self) -> None:
        """Test case for get_condensed_model_scan_reports

        Get condensed reports for a Model Scan
        """
        pass

    def test_get_scan_jobs(self) -> None:
        """Test case for get_scan_jobs

        List all Model Scan Jobs
        """
        pass

    def test_get_scan_results(self) -> None:
        """Test case for get_scan_results

        Get Result of a Model Scan
        """
        pass

    def test_get_scan_results1(self) -> None:
        """Test case for get_scan_results1

        Retrieve Model Scan Results
        """
        pass

    def test_modelscanner_api_v3_health_check(self) -> None:
        """Test case for modelscanner_api_v3_health_check

        Health check endpoint for Model Supply Chain Services
        """
        pass

    def test_modelscanner_api_v3_readiness_check(self) -> None:
        """Test case for modelscanner_api_v3_readiness_check

        Readiness check endpoint for Model Supply Chain Services
        """
        pass

    def test_notify_model_scan_completed(self) -> None:
        """Test case for notify_model_scan_completed

        Indicate part (file or files) of a model scan has completed
        """
        pass

    def test_notify_model_scan_started(self) -> None:
        """Test case for notify_model_scan_started

        Indicate model scan has started
        """
        pass

    def test_report_scan_results(self) -> None:
        """Test case for report_scan_results

        Engine Report Endpoint of Model Scan Results
        """
        pass


if __name__ == '__main__':
    unittest.main()
