# coding: utf-8

"""
    HiddenLayer Sensor SOR

    HiddenLayer Sensor SOR API for operations to sensor data storage

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hiddenlayer.sdk.rest.api.readiness_api import ReadinessApi


class TestReadinessApi(unittest.TestCase):
    """ReadinessApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ReadinessApi()

    def tearDown(self) -> None:
        pass

    def test_modelscanner_api_v3_readiness_check(self) -> None:
        """Test case for modelscanner_api_v3_readiness_check

        Readiness check endpoint for Model Supply Chain Services
        """
        pass


if __name__ == '__main__':
    unittest.main()
