# coding: utf-8

"""
    HiddenLayer-API

    HiddenLayer-API

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hiddenlayer.sdk.rest.models.begin_multi_file_upload200_response import BeginMultiFileUpload200Response

class TestBeginMultiFileUpload200Response(unittest.TestCase):
    """BeginMultiFileUpload200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BeginMultiFileUpload200Response:
        """Test BeginMultiFileUpload200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BeginMultiFileUpload200Response`
        """
        model = BeginMultiFileUpload200Response()
        if include_optional:
            return BeginMultiFileUpload200Response(
                scan_id = ''
            )
        else:
            return BeginMultiFileUpload200Response(
        )
        """

    def testBeginMultiFileUpload200Response(self):
        """Test BeginMultiFileUpload200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
