# coding: utf-8

"""
    HiddenLayer-API

    HiddenLayer-API

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hiddenlayer.sdk.rest.models.translation_metadata import TranslationMetadata

class TestTranslationMetadata(unittest.TestCase):
    """TranslationMetadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TranslationMetadata:
        """Test TranslationMetadata
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TranslationMetadata`
        """
        model = TranslationMetadata()
        if include_optional:
            return TranslationMetadata(
                name = '',
                full_name = '',
                short_description = hiddenlayer.sdk.rest.models.multiformat_message_string.multiformatMessageString(
                    text = '', 
                    markdown = '', 
                    properties = { }, ),
                full_description = hiddenlayer.sdk.rest.models.multiformat_message_string.multiformatMessageString(
                    text = '', 
                    markdown = '', 
                    properties = { }, ),
                download_uri = '',
                information_uri = '',
                properties = { }
            )
        else:
            return TranslationMetadata(
                name = '',
        )
        """

    def testTranslationMetadata(self):
        """Test TranslationMetadata"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
