global:
  namespace: hl-aisec-platform
  registry: quay.io/hiddenlayer
  ttlSecondsAfterFinished: 120
  helmfile:
    mode: apply
  authentication:
    username: ${QUAY_USERNAME}
    password: ${QUAY_PASSWORD}

modelscanner:
  orchestrator:
    license: ${HL_LICENSE}
    k8s:
      resources:
        requests:
          memory: 256Mi
    engine:
      aws:
        bucket: hl-adhoc-model-stage
      k8s:
        resources:
          requests:
            cpu: "1"
            memory: 256Mi
  minio:
    enable: true
