kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

name: test-cluster
nodes:
  - role: control-plane
  - role: worker
    labels:
      topology.kubernetes.io/zone: abc
  - role: worker
    labels:
      topology.kubernetes.io/zone: us-central1-a
